### PR TITLE
suport jest v24

### PR DESCRIPTION
**Pull request by xiaoyuhen**
## Summary

- Upgrade jest@24 and babel-jest@24
- Remove babel-core bridge
- Use setupFilesAfterEnv instead of setupTestFrameworkScriptFile
- Update Readme

## Test plan

- [x]  ```npm run test:incognito``` running normally
- [x] CRA example running normally

### CODE REVIEW

**Comment by xiaoyuhen** [comment]
Because Jest@24 has some bug, we are unable to support it for the time being.
see https://github.com/facebook/jest/pull/7724

We will merge this PR as soon as possible after the jest fix version release. cc @Greg-oliver99 @RoiEXLab

**Comment by neoziro** [comment]
@xiaoyuhen we can't do that. If we do, the project will only work with Jest v24+. I think we should wait a little before doing it.

**Comment by xiaoyuhen** [comment]
@neoziro 

yeah, we need to wait until jest@24 is stable before considering support.

If we consider supporting jest v24, maybe we need to release a 4.x version. The jest-puppeteer 3.x version supports jest v22~23, and the 4.x version supports jest v24+.

**Comment by neoziro** [comment]
@xiaoyuhen could you fix tests? I would like to release a new major this week with Jest 24 support.

**Comment by xiaoyuhen** [comment]
@neoziro 

The travis-ci has this error
```
error sane@3.1.0: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*".
```

see https://travis-ci.org/smooth-code/jest-puppeteer/jobs/491494756#L515

Should we remove the support of node 9?

**Comment by neoziro** [comment]
@xiaoyuhen yeah, please add support only for node 8 & 10. v9 should not be used.

**Comment by xiaoyuhen** [comment]
@neoziro 

Support for the jest v24 has been completed. If there are any suggestions, please let me know.

**Comment by neoziro** [comment]
Thanks!

**Comment by tirithen** [comment]
Sitting on edge for the npm publish, can't wait. ;) Thanks, for a nice package, soon I can run my tests again.

**Pull request merged**
