### PR TITLE
fix: start/stop devServer on watch mode (fixes #229)

### LINKED ISSUE #229: In `watch` mode server doesn't start
## 🐛 Bug Report

If I specify a server and start `jest` in the `watch` mode, the server seems to not start at all.

## To Reproduce

It's reproducable in the create-react-app example. Clone the `jest-puppeteer` repo, move to `examples/create-react-app`, install modules and run `npm run test:integrationWithWatch`. It will fail, although `npm run test:integration` will work fine.

## Expected behavior

`npm run test:integrationWithWatch` should pass

## Link to repl or repo (highly encouraged)

https://github.com/smooth-code/jest-puppeteer/tree/cc9bbfa493349cc88273120996e713523cf86714/examples/create-react-app

## Run `npx envinfo --system --binaries --npmPackages expect-puppeteer,jest-dev-server,jest-environment-puppeteer,jest-puppeteer,spawnd --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS Mojave 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 1.08 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - jest-puppeteer: ^3.7.0 => 3.9.1
```

### PR DESCRIPTION
**Pull request by FezVrasta**
## Summary

The commit that introduced this change broken this functionality, this reverts the minimum amount of code to make it work again.

## Test plan

Verified locally.

### CODE REVIEW

**Comment by lakesare** [comment]
This solution introduces its own issues sadly, the server from `jest-puppeteer.config.js` won't get started at all in watch mode.

**Comment by lakesare** [comment]
This solution introduces its own issues sadly, in watch mode it will raise `Error [ERR_STREAM_WRITE_AFTER_END]: write after end` upon saving some .test.js file.

**Comment by FezVrasta** [comment]
Isn’t that better than not having watch at all? 

Also, the other fix completely breaks this functionality, which otherwise works just fine. So it’s that’s fix that should be reverted.

**Comment by lakesare** [comment]
> So it’s that’s fix that should be reverted.
I agree!
Your PR helped me see how to make jest-puppeteer work on saves too 👍.
I just created the PR that works in both of these cases (https://github.com/smooth-code/jest-puppeteer/pull/299).

**Pull request closed without merging**
