### PR TITLE
Mention @types/expect-puppeteer in readme

### PR DESCRIPTION
**Pull request by testerez**
It took me a few minutes to figure this out so I figured it would help next TS users...

### CODE REVIEW

**Comment by neoziro** [comment]
Thanks!

**Comment by justinbarry** [comment]
@neoziro Any objection to having the types in this repo? If not, I can file a pr.

**Comment by neoziro** [comment]
@justinbarry no I prefer

**Comment by justinbarry** [comment]
Very well, thank you for your quick response.

**Pull request merged**
