### PR TITLE
Allow to use puppeteer-core

### PR DESCRIPTION
**Pull request by mtsmfm**
## Summary

ref: https://github.com/smooth-code/jest-puppeteer/issues/153

I know this PR lacks changing documents though,
it's just my initial idea to move forward.

## Test plan

I already used this patch via my forked package in my project.

https://www.npmjs.com/package/@mtsmfm/jest-environment-puppeteer

### CODE REVIEW

**Comment by mtsmfm** [comment]
@neoziro Can you give me your opinion?

**Comment by neoziro** [comment]
Hello @mtsmfm, I think moving Puppeteer to optionalDependencies is not a good thing, this is not what it is. Also it could create incompatibility issue (https://github.com/smooth-code/jest-puppeteer/issues/153#issuecomment-441312014). I will think about it, but if there is a way to use `puppeteer-core` by aliasing `puppeteer`, I think it is a better solution.

I don't see the gain of using `puppeteer-core` instead of `puppeteer` except avoid downloading a copy of Chromium locally.

**Comment by gidztech** [comment]
It would be cool if there was a way to specify one or the other as a peer dependency. Maybe there is and I don't know? Perhaps you could keep `puppeteer` in `peerDependencies` and then `puppeteer-core` in `optionalDependencies`, since peer dependencies don't get installed automatically (in npm 3+).

**Comment by mtsmfm** [comment]
> I think moving Puppeteer to optionalDependencies is not a good thing

Hmm, I thought all `peerDependencies` should be installed though 🤔 
I moved them into `peerDependencies`.

> Also it could create incompatibility issue

I think writing a note in the document is enough.

**Comment by mtsmfm** [comment]
@gidztech 

> It would be cool if there was a way to specify one or the other as a peer dependency. Maybe there is and I don't know?

AFAIK, there's no way 😢

**Comment by neoziro** [comment]
With yarn, you can alias one package, I think it is the solution. You can alias `puppeteer` to `puppeteer-core` and it will work out of the box. No need to modify `jest-puppeteer` code.

**Comment by mtsmfm** [comment]
@neoziro You meant this, right?

https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias

If so, how about npm?

**Comment by neoziro** [comment]
Yes I mean this, I don't know how to do it using npm, so you will have to use yarn, sorry.

**Pull request closed without merging**
