### PR TITLE
Add external google as an example

### PR DESCRIPTION
**Pull request by escapedcat**
## Summary

Tried to get [the google example](https://github.com/smooth-code/jest-puppeteer#usage) to work locally but failed.  
Tried to make it work in the example tests but also failed:

```sh
 FAIL  integration/external.test.js (7.535 s)
  ● Google › should display "google" text on page

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● Google › should display "google" text on page

    Execution context was destroyed, most likely because of a navigation.



Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   0 total
Time:        8.341 s
```

It would be great if the google example test could also be maintained in the example tests.  
All local tests are still working fine.  
I'm happy to adjust this or integrate feedback.

### CODE REVIEW

**Comment by UziTech** [comment]
Can you resolve the conflict? then I think this looks good! :100:

**Comment by escapedcat** [comment]
> Can you resolve the conflict? then I think this looks good! 💯

Sure, done!  
My main issue is that the "external google" test fails and I don't know why. Happy to change things.

**Comment by UziTech** [comment]
The test seems to work fine for me. What version of jest and puppeteer are you using when it is failing?

**Comment by escapedcat** [comment]
> The test seems to work fine for me. 

Oh nice, that's good to know!

> What version of jest and puppeteer are you using when it is failing?

In `examples/create-react-app` I have:
```sh
...
├─ jest@26.6.0
...
├─ jest-environment-puppeteer@6.0.3
├─ jest-puppeteer@6.1.0
├─ puppeteer@14.4.1
...
```
I'm always getting the "Timeout - Async callback was not invoked within the 5000 ms timeout specified..." error mentioned above when running `yarn test:integration`.  
Maybe I'm doing something wrong.

**Comment by escapedcat** [comment]
Had a look again, tried a couple of times and got this in between:
```sh
 PASS  integration/app.test.js
 PASS  integration/external.test.js (7.674 s)

Test Suites: 2 passed, 2 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        9.283 s
```
I believe it might be related to my connection. It's failing 90% of timesbut if it works once and it's green here in CI anyways it's all good. Thanks! Happy if you merge this.

Thanks for your work!

**Comment by escapedcat** [comment]
In the [external usage example](https://github.com/smooth-code/jest-puppeteer#usage) it says to `import 'expect-puppeteer'` but in this PR it works fine without. I assume that's because it comes with jest-puppeteer already? If yes, shoudl the `import...` be removed from the README?

**Pull request closed without merging**
