### PR TITLE
fix: allow Puppeteer 4

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by fernandopasik** [comment]
@gregberge any chance this could be reviewed?

**Comment by amhunt** [comment]
@gregberge @jsfez Sorry to ping again - do you mind reviewing this? This issue is resulting in a warning whenever someone installs packages in my company's repo. Should be a very quick review - I can attest that this package already works with Puppeteer 4. 😄

**Comment by gaaliche** [comment]
> @gregberge @jsfez Sorry to ping again - do you mind reviewing this? This issue is resulting in a warning whenever someone installs packages in my company's repo. Should be a very quick review - I can attest that this package already works with Puppeteer 4. 😄

@gregberge @jsfez I as well would very much appreciate having this reviewed and merged.
Thanks guys.

**Comment by fernandopasik** [comment]
Puppeteer in version 5 already, would it be good to update the pr @FezVrasta to that?

**Comment by gaaliche** [comment]
@FezVrasta any plans to update this PR to Puppeteer v5 and merge it?
@gregberge FYI

**Comment by FezVrasta** [comment]
What's the point of updating the PR if none of the maintainers ever bothered to take a look at it?

**Comment by lukasoppermann** [comment]
Please @gregberge update this. It currently blocks me from running my tests. 😢

**Comment by siddharthvp** [comment]
Puppeteer is now in v7. I am able to use this package with v7 (though I have only not used this much).

With the [new version of npm (also v7)](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/) now also installing peer dependencies, `npm install` on a project with puppeteer >3 and jest-puppeteer fails completely. 

It would be great if this can be fixed now.

**Review by gregberge — CHANGES_REQUESTED** [review]
"< 4" actually does not includes 4, are you sure?

**Comment by gregberge** [comment]
Guys, there is 0 backer on this project from the start, when it was actually maintain. I don't use it, so I don't maintain it. Become maintainer or do you own Puppeteer integration, sorry!

**Pull request closed without merging**
