### PR TITLE
fix: Cannot read property watch of undefined in jest v22 version

### PR DESCRIPTION
**Pull request by xiaoyuhen**
## Summary

close https://github.com/smooth-code/jest-puppeteer/issues/195

## Test plan

- [x] Jest-puppeteer works fine in jest v22 version
- [x] Jest-puppeteer works fine in jest v23 version

### CODE REVIEW

**Comment by neoziro** [comment]
Thanks!

**Comment by xiaoyuhen** [comment]
@neoziro 

should we also publish a 3.9.1 version to resolve this bug? because 4.0.0 version only support jest v24+

**Comment by neoziro** [comment]
I don't think so, it doesn't worth it. Migrating to Jest 24 is not a big deal.

**Comment by xiaoyuhen** [comment]
@neoziro 

yeah, upgrade Jest is not a big deal, but if we dont plan to support Jest v22, should we update the README  to explain this?

**Comment by neoziro** [comment]
@xiaoyuhen I think the readme is enough clear about that. We will just drop the line about Jest v22 in one or two months and it will be enough.

**Pull request merged**
