### PR TITLE
feat(jest-environment-puppeteer): added config option for global err msg

### LINKED ISSUE #34: Make global error handler configurable
As mentioned in #31, global error message are thrown.

The idea is to add a `exitOnPageError` flag into [jest-puppeteer.config.js](https://github.com/smooth-code/jest-puppeteer#jest-puppeteerconfigjs). This flag will be `true` by default.

If `true`, [this line](https://github.com/smooth-code/jest-puppeteer/blob/master/packages/jest-environment-puppeteer/src/PuppeteerEnvironment.js#L24) is effective, if not, this line is not effective.

### PR DESCRIPTION
**Pull request by kaufmann42**
Closes #34

### CODE REVIEW

**Comment by neoziro** [comment]
Thanks, can you default it to `true`?

**Comment by kaufmann42** [comment]
Will do.

**Comment by kaufmann42** [comment]
Went ahead and added.

**Comment by neoziro** [comment]
Thanks!

**Comment by linusrachlis** [comment]
Hi @neoziro ,

Just curious what's the thinking behind having this default to `true`. Should any page-level JS error be considered a test failure? Sadly these days, it's a rare website that has no JS errors, and sometimes they are caused by external libraries out of the developer's control. I would have thought the more common case would be that you _don't_ want the browser to exit on a page-level error, although some people might want the option to do so. What do you think?

Thanks,
Linus

**Comment by neoziro** [comment]
Hello @linusrachlis, I think it is better to encourage user to not have uncaught errors in console. Anyway now you have the choice but defaulting to `true` encourages best practice.

**Pull request merged**
