### PR TITLE
fix: Jest --watch fails to reload

### PR DESCRIPTION
**Pull request by xiaoyuhen**
## Summary

close https://github.com/smooth-code/jest-puppeteer/issues/181

## Test plan

- ```npm run test:integrationWithWatch``` is running normally in cra example

### CODE REVIEW

**Comment by neoziro** [comment]
@xiaoyuhen I don't understand why we don't launch the server in watchMode?

**Comment by neoziro** [comment]
OK Thanks!

**Comment by nicoalurralde** [comment]
I get "TypeError: Cannot read property 'watch' of undefined" with this fix. What am I missing?

**Comment by neoziro** [comment]
It will be fixed in next release.

**Comment by nicoalurralde** [comment]
Thanks, just realised I needed to update Jets to 23.6.0 for a quick fix

**Pull request merged**
