### PR TITLE
Only run findProcess where required in order to avoid prompting for super user login

### PR DESCRIPTION
**Pull request by mzedeler**
## Summary

Avoid prompting for super user password when possible.

## Test plan

TBD

### CODE REVIEW

**Comment by mzedeler** [comment]
I *really* have an issue with tools that suddenly prompt for a password. This is a perfect attack vector for hackers. I think it would be a good idea to ensure that nobody is ever prompted for password.

**Comment by mzedeler** [comment]
I'll fix the tests tomorrow.

**Comment by mzedeler** [comment]
I've updated the code now. The tests should run and I've improved the handling of the case where the ports are in use, so calling `findProcess` is done as late as possible.

**Comment by mzedeler** [comment]
I've run some manual testing to verify that the different configuration options work, but it would be a good idea to add tests for them.

**Comment by neoziro** [comment]
@mzedeler thanks! Yes but it is very difficult to test it 😔

**Pull request merged**
