### PR TITLE
Separated jest-dev-server into its own package

### LINKED ISSUE #66: Add jest-dev-server into packages
Like discussed in #62, it would be nice to have `jest-dev-server` as standalone.

The job is already done (https://github.com/JoshuaKGoldberg/jest-dev-server).

This issue consist by creating it into packages and use it into `jest-puppeteer-environment` as a dependency.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #66.

I'm not sure I hooked up everything correctly (never used lerna before; rarely use babel). Would appreciate a stringent review :smile:!

### CODE REVIEW

**Comment by neoziro** [comment]
Good job! I just gave a quick look, it looks OK. I will take a deeper look and merge it this week end. Thanks 🙏

**Comment by JoshuaKGoldberg** [comment]
Ping @neoziro  - anything I can do to help?

**Comment by JoshuaKGoldberg** [comment]
Just a heads up, I ended up needing #71 and added it to jest-dev-server. When this goes in, please don't publish a new version with these changes immediately before we get that feature added in first!

Will edit this post if I end up adding more things to jest-dev-server upstream.

**Comment by neoziro** [comment]
@JoshuaKGoldberg OK, I am on it, I think it will done by the end of month.

**Pull request merged**
