### PR TITLE
feat(expect-puppeteer): use helper that keep original error message

### PR DESCRIPTION
**Pull request by kytwb**
Related to #33.

### CODE REVIEW

**Comment by kytwb** [comment]
@neoziro I need to write some tests and add a notice in the README.  
Is that `errorHandler` I introduced ok though? Feedback welcome.

**Comment by neoziro** [comment]
All errors are wrapped, it is a good first step. Second step, we need to display the original error to the user, in order to simplify debug. I think displaying the `originalError.stack` should be sufficient.

**Comment by kytwb** [comment]
@neoziro What I did is incorrect I think, I can't just add an attribute like this to an `Error` object, I guess I have to extend it - tried to `console.log` the added attribute but it's undefined. When you say "displaying the `originalError.stack`", do you mean `console.log`/`console.error`-ing it?

**Comment by neoziro** [comment]
I did it in #45, thanks for your time and sorry for not having merged your PR.

**Pull request closed without merging**
